language: ruby
sudo: false

before_install:
  - gem update --system

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

cache:
  bundler: true

install:
  - bundle install

script:
  - bundle exec rake
