language: ruby
sudo: false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

cache:
  bundler: true

gemfile:
  - gemfiles/rails_5.0.x.gemfile
  - gemfiles/rails_5.1.x.gemfile
  - gemfiles/rails_5.2.x.gemfile
  - gemfiles/rails_6.0.x.gemfile

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_6.0.x.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_6.0.x.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.x.gemfile

install:
  - bundle install

script:
  - bundle exec rake test:all_with_coverage
